# Daily Opportunity Research Scheduler
# This script triggers the freestyle opportunity research session

param(
    [string]$ResearchMode = "auto",  # auto, manual, or prompted
    [string]$OutputPath = "C:\Users\impro\.openclaw\workspace\opportunity-research"
)

$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$logFile = "$OutputPath\scheduler-log.txt"

# Log start
Add-Content -Path $logFile -Value "[$timestamp] Research session triggered"

# Check if user is available (optional - can be skipped for auto mode)
if ($ResearchMode -eq "prompted") {
    Write-Host "🎯 Daily Opportunity Research Session"
    Write-Host "Time: $timestamp"
    Write-Host ""
    Write-Host "Press Enter to begin research or Ctrl+C to skip..."
    $null = Read-Host
}

# Create session marker
$sessionFile = "$OutputPath\sessions\session-$(Get-Date -Format 'yyyy-MM-dd').md"
New-Item -ItemType Directory -Path "$OutputPath\sessions" -Force | Out-Null

$template = @"
# Research Session — $(Get-Date -Format 'yyyy-MM-dd')

**Status:** TRIGGERED
**Time:** $timestamp
**Mode:** $ResearchMode

## Session Ready
Awaiting user input to begin research.

Run command: 
`freestyle-research --streams healthcare,aviation --generate 3`

---
*Auto-generated by scheduler*
"@

Set-Content -Path $sessionFile -Value $template

Add-Content -Path $logFile -Value "[$timestamp] Session marker created: $sessionFile"

Write-Host "✅ Research session scheduled for today"
Write-Host "📁 Session file: $sessionFile"
Write-Host ""
Write-Host "Next steps:"
Write-Host "1. Review yesterday's research"
Write-Host "2. Select today's stream domains"
Write-Host "3. Generate concepts"
